GET {{host}} HTTP/1.1

###

POST {{host}}/sign-up HTTP/1.1
Content-Type: application/json

{
  "email": "{{email}}",
  "password": "{{password}}",
  "name": "{{name}}"
}

###

POST {{host}}/login HTTP/1.1
Content-Type: application/json

{
  "email": "{{email}}",
  "password": "{{password}}"
}

###
POST {{host}}/refresh HTTP/1.1
Authorization: {{refreshToken}}

###
POST {{host}}/logout HTTP/1.1
Authorization: {{refreshToken}}


###
POST {{host}}/users HTTP/1.1
Authorization: {{accessToken}}

###
POST {{host}}/wallet/fund HTTP/1.1
Authorization: {{refreshToken}}

{
  "walletId": 1,
  "amount": 4000
}

###
POST {{host}}/wallet/transfer HTTP/1.1
Authorization: {{refreshToken}}

{
  "recipientWalletId": 3,
  "walletId": 1,
  "amount": 4000
}

###
POST {{host}}/wallet/withdraw HTTP/1.1
Authorization: {{refreshToken}}

{
  "walletId": 1,
  "amount": 4000
}